EMAIL_MAX_LENGTH = 254
MAX_LENTH = 150
FORBIDDEN_NAME = 'me'
VALID_USERNAME_PATTERN = r'^[\w.@+-]+\Z'

LENG_SLUG = 50
LENG_MAX = 256
LENG_DATA_USER = 150
LENG_EMAIL = 254
LENG_CUT = 30

MESSAGE_EMAIL_EXISTS = 'Этот email уже занят'
MESSAGE_USERNAME_EXISTS = 'Это имя уже занято'